import keyMirror from 'keymirror';

export default keyMirror({
	GAME10_OFFLINE_INIT_GAME						: null,
	GAME10_OFFLINE_INIT_START_GAME					: null,
	GAME10_OFFLINE_DISPLAY_GAME_STATE				: null,

	GAME10_OFFLINE_INIT_ROUND						: null,
	GAME10_OFFLINE_INIT_ROUND_SUCCESS				: null,

	GAME10_OFFLINE_PLAY_CARD 						: null,
	GAME10_OFFLINE_PLAY_CARD_SUCCESS				: null,
	GAME10_OFFLINE_PLAY_CARD_ERROR					: null,

	GAME10_OFFLINE_DISTRIBUTE_CARDS				: null,
	GAME10_OFFLINE_DISTRIBUTE_CARDS_SUCCESS		: null,
	GAME10_OFFLINE_DISTRIBUTE_CARDS_ERROR			: null,

	GAME10_OFFLINE_CHECK_BOT_PLAY					: null,
	GAME10_OFFLINE_BOT_WILL_PLAY					: null,
	GAME10_OFFLINE_BOT_HAS_PLAYED					: null,

	GAME10_OFFLINE_SKIP_TURN						: null,
	GAME10_OFFLINE_TURN_SKIPPED					: null,

	GAME10_OFFLINE_NOW_NEXT_TURN					: null,
	GAME10_OFFLINE_END_TURN						: null,

	GAME10_OFFLINE_SHOW_SCORES						: null,
	GAME10_OFFLINE_WAIT_TO_SHOW_SCORE				: null,

	GAME10_OFFLINE_TOGGLE_PAUSE					: null,

	GAME10_ONLINE_GAME_STATE_RECEIVED				: null,
	GAME_7_ONLINE_INIT_ROUND				: null,
	GAME10_ONLINE_NOW_NEXT_TURN: null,

	GAME10_ONLINE_DISTRIBUTE_CARDS_SUCCESS		: null,

	GAME10_ONLINE_PLAY_CARD: null,
	GAME10_ONLINE_CARD_PLAYED: null,
	GAME10_ONLINE_PLAY_CARD_SUCCESS: null,
	
	GAME_10_ONLINE_PLAYED_WAIT_FOR_SERVER: null,

	GAME_10_ONLINE_SKIP_TURN: null,
	GAME_10_ONLINE_TURN_SKIPPED: null,
	GAME_10_ONLINE_SKIP_TURN_DONE: null,

	GAME_10_ONLINE_SHOW_SCORES: null,

	GAME_10_ONLINE_INIT_ROUND_SUCCESS: null,

	GAME_10_ONLINE_SHOW_SCORES_WAIT_FOR_SERVER: null,

	GAME_10_OFFLINE_HIDE_SCORE_UPDATED: null,
	GAME_10_ONLINE_HIDE_SCORE_UPDATED: null,

	GAME_10_ONLINE_PLAYER_CHANGED: null,
	GAME_10_ONLINE_REQUEST_SERVER_BOT: null,

	GAME10_ONLINE_ADMIN_REQUEST_DISTRIBUTION: null,
	GAME_10_REFRESH_STORE: null,
	"nn": null

});