import keyMirror from 'keymirror';

export default keyMirror({
  REQUEST_USER: null,
  REQUEST_USER_SUCCESS: null,
  REQUEST_USER_ERROR: null,

  REQUEST_REPO: null,
  REQUEST_REPO_SUCCESS: null,
  REQUEST_REPO_ERROR: null,

  REQUEST_STARRED_REPOS_PAGE: null,
  REQUEST_STARRED_REPOS_PAGE_SUCCESS: null,
  REQUEST_STARRED_REPOS_PAGE_ERROR: null,

  REQUEST_STARGAZER_PAGE: null,
  REQUEST_STARGAZER_PAGE_SUCCESS: null,
  REQUEST_STARGAZER_PAGE_ERROR: null,

  UPDATE_CREDENTIALS : null,

  LOGGED_IN : null,

  LOGIN_REQUEST : null,
  LOGGED_IN_WITH_FB_ERROR : null,
  LOGGED_IN_WITH_FB : null,

  LOG_OUT : null,
  LOGGED_OUT : null,

  CREATE_ROOM_REQ : null,
  CREATE_ROOM_REQ_SUCCESS : null,
  CREATE_ROOM_REQ_ERROR : null,
  
  JOIN_ROOM_REQ : null,
  JOIN_ROOM_REQ_SUCCESS : null,
  JOIN_ROOM_REQ_ERROR : null,
  
  EXIT_ROOM_REQ : null,
  EXIT_ROOM_REQ_SUCCESS : null,
  EXIT_ROOM_REQ_ERROR : null
});
      