import keyMirror from 'keymirror';

export default keyMirror({
  REQUEST_USER: null,
  REQUEST_USER_SUCCESS: null,
  REQUEST_USER_ERROR: null,

  REQUEST_REPO: null,
  REQUEST_REPO_SUCCESS: null,
  REQUEST_REPO_ERROR: null,

  REQUEST_STARRED_REPOS_PAGE: null,
  REQUEST_STARRED_REPOS_PAGE_SUCCESS: null,
  REQUEST_STARRED_REPOS_PAGE_ERROR: null,

  REQUEST_STARGAZER_PAGE: null,
  REQUEST_STARGAZER_PAGE_SUCCESS: null,
  REQUEST_STARGAZER_PAGE_ERROR: null,

  UPDATE_CREDENTIALS : null,

  LOGGED_IN : null,

  LOGIN_REQUEST : null,
  LOGGED_IN_WITH_FB_ERROR : null,
  LOGGED_IN_WITH_FB : null,

  LOG_OUT : null,
  LOGGED_OUT : null,

  CREATE_ROOM_REQ : null,
  CREATE_ROOM_REQ_SUCCESS : null,
  CREATE_ROOM_REQ_ERROR : null,
  
  JOIN_ROOM_REQ : null,
  JOIN_ROOM_REQ_SUCCESS : null,
  JOIN_ROOM_REQ_ERROR : null,
  
  EXIT_ROOM_REQ : null,
  EXIT_ROOM_REQ_SUCCESS : null,
  EXIT_ROOM_REQ_ERROR : null,

  GET_ROOM_REQ : null,
  GET_ROOM_REQ_SUCCESS : null,
  GET_ROOM_REQ_ERROR : null,

  FETCH_SCORES_FROM_SERVER: null,
  GAMESCORE_FETCH_REQUEST: null,
  GAMESCORE_FETCH_SUCCESS: null,
  GAMESCORE_FETCH_ERROR: null,

  GAMESCORE_UPDATE_REQUEST: null,
  GAMESCORE_UPDATE_SUCCESS: null,
  GAMESCORE_UPDATE_ERROR: null,

  CHANGE_SETTINGS: null,

  UPDATE_SELECTED_GAME : null,
  
  GAME325 : null,
});
      