import keyMirror from 'keymirror';

export default keyMirror({
	GAME325_INIT_GAME						: null,
	GAME325_INIT_START_GAME					: null,
	GAME325_DISPLAY_GAME_STATE				: null,

	GAME325_INIT_ROUND						: null,
	GAME325_INIT_ROUND_SUCCESS				: null,

	GAME325_PLAY_CARD 						: null,
	GAME325_PLAY_CARD_SUCCESS				: null,
	GAME325_PLAY_CARD_ERROR					: null,

	GAME325_DISTRIBUTE_CARDS				: null,
	GAME325_DISTRIBUTE_CARDS_SUCCESS		: null,
	GAME325_DISTRIBUTE_CARDS_ERROR			: null,

	GAME325_CHECK_BOT_PLAY					: null,
	GAME325_BOT_WILL_PLAY					: null,
	GAME325_BOT_HAS_PLAYED					: null,

	GAME325_SKIP_TURN						: null,
	GAME325_TURN_SKIPPED					: null,

	GAME325_NOW_NEXT_TURN					: null,
	GAME325_END_TURN						: null,

	GAME325_SHOW_SCORES						: null,
	GAME325_WAIT_TO_SHOW_SCORE				: null,

	GAME325_TOGGLE_PAUSE					: null,

	GAME325_DISTRIBUTE_ONE_CARD_EACH		: null,
	GAME325_SELECT_DEALER					: null,

	GAME325_SELECT_DEALER_SUCCESS			: null,

	GAME325_START_GAME 						: null,

	GAME325_SET_TRUMP						: null,

	GAME325_DISTRIBUTE_CARDS_ZERO_SUCCESS	: null,

	GAME325_DISTRIBUTE_CARDS_FIRST_SUCCESS	: null,

	GAME325_DISTRIBUTE_CARDS_SECOND_SUCCESS  : null,

	GAME325_MOVE_HAND						: null,
	GAME325_MOVE_HAND_SUCCESS				: null,

	GAME325_WITHDRAW_CARD 					: null,
	GAME325_WITHDRAW_CARD_SUCCESS			: null,
	
	GAME325_RETURN_CARD 					: null,
	GAME325_RETURN_CARD_SUCCESS 			: null,

	GAME325_ONLINE_INIT_GAME						: null,
	GAME325_ONLINE_INIT_START_GAME					: null,
	GAME325_ONLINE_DISPLAY_GAME_STATE				: null,

	GAME325_ONLINE_INIT_ROUND						: null,
	GAME325_ONLINE_INIT_ROUND_SUCCESS				: null,

	GAME325_ONLINE_PLAY_CARD 						: null,
	GAME325_ONLINE_PLAY_CARD_SUCCESS				: null,
	GAME325_ONLINE_PLAY_CARD_ERROR					: null,

	GAME325_ONLINE_DISTRIBUTE_CARDS				: null,
	GAME325_ONLINE_DISTRIBUTE_CARDS_SUCCESS		: null,
	GAME325_ONLINE_DISTRIBUTE_CARDS_ERROR			: null,

	GAME325_ONLINE_CHECK_BOT_PLAY					: null,
	GAME325_ONLINE_BOT_WILL_PLAY					: null,
	GAME325_ONLINE_BOT_HAS_PLAYED					: null,

	GAME325_ONLINE_SKIP_TURN						: null,
	GAME325_ONLINE_TURN_SKIPPED					: null,

	GAME325_ONLINE_NOW_NEXT_TURN					: null,
	GAME325_ONLINE_END_TURN						: null,

	GAME325_ONLINE_SHOW_SCORES						: null,
	GAME325_ONLINE_WAIT_TO_SHOW_SCORE				: null,

	GAME325_ONLINE_TOGGLE_PAUSE					: null,

	GAME325_ONLINE_DISTRIBUTE_ONE_CARD_EACH		: null,
	GAME325_ONLINE_SELECT_DEALER					: null,

	GAME325_ONLINE_SELECT_DEALER_SUCCESS			: null,

	GAME325_ONLINE_START_GAME 						: null,

	GAME325_ONLINE_SET_TRUMP						: null,

	GAME325_ONLINE_DISTRIBUTE_CARDS_ZERO_SUCCESS	: null,

	GAME325_ONLINE_DISTRIBUTE_CARDS_FIRST_SUCCESS	: null,

	GAME325_ONLINE_DISTRIBUTE_CARDS_SECOND_SUCCESS  : null,

	GAME325_ONLINE_MOVE_HAND						: null,
	GAME325_ONLINE_MOVE_HAND_SUCCESS				: null,

	GAME325_ONLINE_WITHDRAW_CARD 					: null,
	GAME325_ONLINE_WITHDRAW_CARD_SUCCESS			: null,
	
	GAME325_ONLINE_RETURN_CARD 					: null,
	GAME325_ONLINE_RETURN_CARD_SUCCESS 			: null,

	GAME325_ONLINE_GAME_STATE_RECEIVED 			: null,

	JOIN_ROOM_REQ_SUCCESS						: null,

	GAME325_ONLINE_PLAYER_CHANGED 				: null,

	GAME325_ONLINE_REQUEST_SERVER_BOT 			: null,

	GAME325_ONLINE_ADMIN_REQUEST_DISTRIBUTION 	: null,

	GAME325_ONLINE_SELECT_DEALER_SUCCESS 		: null,

	GAME325_ONLINE_REQUEST_SERVER_BOT 			: null,

	GAME325_ONLINE_SET_TRUMP_SUCCESS 			: null
});
